var listData = {};

listData.listData00= {
	"success":"成功",
	"data":{
		"pageStart":0,
		"pageSize":6,
		"count":71,

		"list":[{
			"titleName":"不屈铁壁",
			"describe":"出身世家望族，才华横溢又深得老师赏识，前途无量。然而同窗们大跌眼镜的是，他选择了投笔从戎。",
			"name":"苏烈",
			"sysId":1,
			"coverImg":"images/list/list_img01.jpg",
			"status":2
			},{
			"titleName":"嚣狂之镰",
			"describe":"本应死于马贼之手，却因神秘人的出现而活了下来，并习得一生强大武技。",
			"name":"百里玄策",
			"sysId":2,
			"coverImg":"images/list/list_img02.jpg",
			"status":2
			},{
			"titleName":"静谧之眼",
			"describe":"他的一生中只有弟弟，弟弟就是他活下去的动力。",
			"name":"百里守约",
			"sysId":3,
			"coverImg":"images/list/list_img03.jpg",
			"status":2
			},{
			"titleName":"破灭刃锋",
			"describe":"他是一个迷失者，没有过去，只能创造未来。",
			"name":"凯",
			"sysId":4,
			"coverImg":"images/list/list_img04.jpg",
			"status":2
			},{
			"titleName":"万物有灵",
			"describe":"他是个智者，一生都在寻求大智慧；曾参与奇迹的建造——转生之术。",
			"name":"鬼谷子",
			"sysId":5,
			"coverImg":"images/list/list_img05.jpg",
			"status":2
			},{
			"titleName":"淬命双剑",
			"describe":"他是一个铸剑师，为了成为最强，为了铸造活的剑，他妻子莫邪放弃了生命，他也...",
			"name":"干将莫邪",
			"sysId":6,
			"coverImg":"images/list/list_img06.jpg",
			"status":2
			}
		]
	}
}

listData.listData01= {
	"success":"成功",
	"data":{ 

		"pageStart":1, 
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"噬灭日蚀",
			"describe":"平凡的身躯，却跳动着一颗执着而冷酷的心;因为他坚信平庸是恶。",
			"name":"东皇太一",
			"sysId":7,
			"coverImg":"images/list/list_img07.jpg",
			"status":2
			},{
			"titleName":"沧海之曜",
			"describe":"应验而生的她，却从未顺从命运，只因她骨子里铭刻着不可思议的高傲和叛逆...",
			"name":"大乔",
			"sysId":8,
			"coverImg":"images/list/list_img08.jpg",
			"status":2
			},{
			"titleName":"燃魂重炮",
			"describe":"人，就是人。一撇一捺，大写的人。他生来就是人，死去，也要以人的身份。",
			"name":"黄忠",
			"sysId":9,
			"coverImg":"images/list/list_img09.jpg",
			"status":2
			},{
			"titleName":"绝代智谋",
			"describe":"稷下学院有史以来最伟大的天才，世间公认夫子的继承者。无论魔道机关，智谋兵法，样样都是第一。",
			"name":"诸葛亮",
			"sysId":10,
			"coverImg":"images/list/list_img10.jpg",
			"status":2
			},{
			"titleName":"桀骜炎枪",
			"describe":"他，是人，又非人；炼金术的身体，无痛无痒，永远都无法长大；可胸腔里跳动着生而为人的心脏。",
			"name":"哪吒",
			"sysId":11,
			"coverImg":"images/list/list_img11.jpg",
			"status":2
			},{
			"titleName":"炼金大师",
			"describe":"吾太乙，天下第一的傻瓜师父，曾经犯下三桩错误。现在，要以生命去填补。",
			"name":"太乙真人",
			"sysId":12,
			"coverImg":"images/list/list_img12.jpg",
			"status":2
			}
		]
	}
}

listData.listData02= {
	"success":"成功",
	"data":{
		"pageStart":2,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"天籁弦音",
			"describe":"黑暗的魔神王会降临大陆，唯有美少女的琴音挥洒希望与胜利。",
			"name":"蔡文姬",
			"sysId":13,
			"coverImg":"images/list/list_img13.jpg",
			"status":2
			},{
			"titleName":"圣域余晖",
			"describe":"我，雅典娜，绝对的信仰。她出身于荣耀的骑士家族，守卫勇士之地已经如同信仰般铭刻入了血脉。",
			"name":"雅典娜",
			"sysId":14,
			"coverImg":"images/list/list_img14.jpg",
			"status":2
			},{
			"titleName":"根源之目",
			"describe":"拥有异于常人的眼，成为守护人间意志的化身，可是人间意志又是什么....",
			"name":"杨戬",
			"sysId":15,
			"coverImg":"images/list/list_img15.jpg",
			"status":2
			},{
			"titleName":"苍狼末裔",
			"describe":"当你凝视深渊的时候 深渊也在凝视你。",
			"name":"成吉思汗",
			"sysId":16,
			"coverImg":"images/list/list_img16.jpg",
			"status":2
			},{
			"titleName":"虚灵城判",
			"describe":"也许它不仅是长安的第一个居民，也是长安真正的主人。",
			"name":"钟馗",
			"sysId":17,
			"coverImg":"images/list/list_img17.jpg",
			"status":2
			},{
			"titleName":"森之风灵",
			"describe":"风起云涌。楚汉之地的风暴，能在历史上永久留下姓名的风暴，刮起来了。"+"<br/>"+"谁是螳螂，谁是黄雀？",
			"name":"虞姬",
			"sysId":18,
			"coverImg":"images/list/list_img18.jpg",
			"status":2
			}
		]
	}
}

listData.listData03= {
	"success":"成功",
	"data":{
		"pageStart":3,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"王都密探",
			"describe":"我付出了代价！他不会....."+"<br/>"+"不过，我心甘情愿。",
			"name":"李元芳",
			"sysId":19,
			"coverImg":"images/list/list_img19.jpg",
			"status":2
			},{
			"titleName":"禁血狂兽",
			"describe":"呵，果然……枷锁也锁不住，养都养不熟的野兽。"+"<br/>"+"最凶残的野兽，不是你我吗？",
			"name":"张飞",
			"sysId":20,
			"coverImg":"images/list/list_img20.jpg",
			"status":2
			},{
			"titleName":"仁德义枪",
			"describe":"‘任时代流转，世事变迁，我等生死之歃，始终不渝。’",
			"name":"刘备",
			"sysId":21,
			"coverImg":"images/list/list_img21.jpg",
			"status":2
			},{
			"titleName":"半神之弓",
			"describe":"重生的太阳，是否会射出更璀璨的光辉?"+"<br/>"+"拭目以待吧。",
			"name":"后羿",
			"sysId":22,
			"coverImg":"images/list/list_img22.jpg",
			"status":2
			},{
			"titleName":"精英酋长",
			"describe":"想念你，可贵的朋友——然而，并不后悔出卖你以换取如今的所有。",
			"name":"牛魔",
			"sysId":23,
			"coverImg":"images/list/list_img23.jpg",
			"status":2
			},{
			"titleName":"齐天大圣",
			"describe":"回应着呼唤与呢喃，大地开始剧烈的颤抖。"+"<br/>"+"就像千百年前诞生时一样，冲破枷锁和束缚。"+"<br/>"+"它的身影如此高大，矗立于天地之间。",
			"name":"孙悟空",
			"sysId":24,
			"coverImg":"images/list/list_img24.jpg",
			"status":2
			}
		]
	}
}

listData.listData04= {
	"success":"成功",
	"data":{
		"pageStart":4,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"圣骑之力",
			"describe":"因剑而生，因剑而亡！",
			"name":"亚瑟",
			"sysId":25,
			"coverImg":"images/list/list_img25.jpg",
			"status":2
			},{
			"titleName":"神梦一刀",
			"describe":"若是只有究极之花才能带回恋人的笑容……",
			"name":"橘右京",
			"sysId":26,
			"coverImg":"images/list/list_img26.jpg",
			"status":2
			},{
			"titleName":"鹰之守护",
			"describe":"如果再这样下去，扶桑，连同自然之灵，都会死去吧。",
			"name":"娜可露露",
			"sysId":27,
			"coverImg":"images/list/list_img27.jpg",
			"status":2
			},{
			"titleName":"明媚烈焰",
			"describe":"流派的安危，心爱的男人，还有爷爷的仇恨，一切，在京都来决断吧！ ",
			"name":"不知火舞",
			"sysId":28,
			"coverImg":"images/list/list_img28.jpg",
			"status":2
			},{
			"titleName":"言灵之书",
			"describe":"他拥有莫大的杀伤力，却不能挣到一文钱；他的思想超越时代，却找不到前进的道路；他能听懂所有语言，却…… ",
			"name":"张良",
			"sysId":29,
			"coverImg":"images/list/list_img29.jpg",
			"status":2
			},{
			"titleName":"传说之刃",
			"describe":"静如影，疾如风。"+"<br/>"+"不动如山，迅烈如火。"+"<br/>"+"前方是无际的长城，以及无际的敌人。",
			"name":"花木兰",
			"sysId":30,
			"coverImg":"images/list/list_img30.jpg",
			"status":2
			}
		]
	}
}

listData.listData05= {
	"success":"成功",
	"data":{
		"pageStart":5,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"暗影刀锋",
			"describe":"一人敌一国，多么荒诞，又是多么简单。 ",
			"name":"兰陵王",
			"sysId":31,
			"coverImg":"images/list/list_img31.jpg",
			"status":2
			},{
			"titleName":"冰雪之华",
			"describe":"她高雅，美丽，明亮的双眸饱含哀伤，纤长的手指拂过.....",
			"name":"王昭君",
			"sysId":32,
			"coverImg":"images/list/list_img32.jpg",
			"status":2
			},{
			"titleName":"国士无双",
			"describe":"不信天，不信命；唯一能相信的，只有自己。",
			"name":"韩信",
			"sysId":33,
			"coverImg":"images/list/list_img33.jpg",
			"status":2
			},{
			"titleName":"双面君主",
			"describe":"他那样另类：既无视信仰，又热衷利益，更不择手段。",
			"name":"刘邦",
			"sysId":34,
			"coverImg":"images/list/list_img34.jpg",
			"status":2
			},{
			"titleName":"太古魔导",
			"describe":"当稷下的青烟在空中飘散之时，遥远的云和山的彼端，似乎永远也打不倒的老人从沉睡中苏醒。",
			"name":"姜子牙",
			"sysId":35,
			"coverImg":"images/list/list_img35.jpg",
			"status":2
			},{
			"titleName":"月光之女",
			"describe":"总有一天，总有一天能再见面吧。我会找到你，然后做一个了结。",
			"name":"露娜",
			"sysId":36,
			"coverImg":"images/list/list_img36.jpg",
			"status":2
			}
		]
	}
}

listData.listData06= {
	"success":"成功",
	"data":{
		"pageStart":6,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"热烈之斧",
			"describe":"只有武艺不足以保卫家乡。当太阳的光辉照耀到每个角落，才会有真正的和平。",
			"name":"程咬金",
			"sysId":37,
			"coverImg":"images/list/list_img37.jpg",
			"status":2
			},{
			"titleName":"暗夜萝莉",
			"describe":"无论如何，我回来了。我要报复，我要找回尊严和自信。",
			"name":"安琪拉",
			"sysId":38,
			"coverImg":"images/list/list_img38.jpg",
			"status":2
			},{
			"titleName":"绝世舞姬",
			"describe":"我在光明中起舞，你是我的烛之影。你在黑暗中厮杀，我是你的月之影。",
			"name":"貂蝉",
			"sysId":39,
			"coverImg":"images/list/list_img39.jpg",
			"status":2
			},{
			"titleName":"一骑当千",
			"describe":"决定了内心的正道，便绝无动摇。",
			"name":"关羽",
			"sysId":40,
			"coverImg":"images/list/list_img40.jpg",
			"status":2
			},{
			"titleName":"万古长明",
			"describe":"夫子所在的地方，就是和平的人间界",
			"name":"老夫子",
			"sysId":41,
			"coverImg":"images/list/list_img41.jpg",
			"status":2
			},{
			"titleName":"女帝",
			"describe":"这个天下，这个世界，以及所有王者梦想的未来统一的理想国，终究都属于她",
			"name":"武则天",
			"sysId":42,
			"coverImg":"images/list/list_img42.jpg",
			"status":2
			}
		]
	}
}

listData.listData07= {
	"success":"成功",
	"data":{
		"pageStart":7,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"霸王",
			"describe":"……等着我吧……虞姬。这一次，再不会有什么诀别。 ",
			"name":"项羽",
			"sysId":43,
			"coverImg":"images/list/list_img43.jpg",
			"status":2
			},{
			"titleName":"拳僧",
			"describe":"他的本性如此，并不重要。然而见性，方能成佛。",
			"name":"达摩",
			"sysId":44,
			"coverImg":"images/list/list_img44.jpg",
			"status":2
			},{
			"titleName":"断案大师",
			"describe":"到达现场精确如钟表，搜查赃物像打扫清洁，审讯犯人如同逻辑课。",
			"name":"狄仁杰",
			"sysId":45,
			"coverImg":"images/list/list_img45.jpg",
			"status":2
			},{
			"titleName":"远游之枪",
			"describe":"旅行者，冒险家，语言天才……人们这样称呼他",
			"name":"马可波罗",
			"sysId":46,
			"coverImg":"images/list/list_img46.jpg",
			"status":2
			},{
			"titleName":"青莲剑仙",
			"describe":"没有机关的师承，没有魔道的秘法，没有魔种的血脉，仅仅依靠自己和手中的剑，成为大唐第一人，乃天纵之才。",
			"name":"李白",
			"sysId":47,
			"coverImg":"images/list/list_img47.jpg",
			"status":2
			},{
			"titleName":"剑圣",
			"describe":"左手一把长刀，右手一把短剑，神挡杀神，魔挡杀魔，取过的人头比吃过的米还多……",
			"name":"宫本武藏",
			"sysId":48,
			"coverImg":"images/list/list_img48.jpg",
			"status":2
			}
		]
	}
}

listData.listData08= {
	"success":"成功",
	"data":{
		"pageStart":8,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"狂战士",
			"describe":"英雄，末路。"+"<br/>"+"取而代之的是…… ",
			"name":"典韦",
			"sysId":49,
			"coverImg":"images/list/list_img49.jpg",
			"status":2
			},{
			"titleName":"鲜血枭雄",
			"describe":"战争是什么？"+"<br/>"+"是铭文？是力量？是权力？"+"<br/>"+"不，这是一场游戏，一场野心与欲望的游戏。",
			"name":"曹操",
			"sysId":50,
			"coverImg":"images/list/list_img50.jpg",
			"status":2
			},{
			"titleName":"洛神降临",
			"describe":"若轻云之蔽月，若流风之回雪。"+"<br/>"+"翩若惊鸿，婉若游龙。",
			"name":"甄姬",
			"sysId":51,
			"coverImg":"images/list/list_img51.jpg",
			"status":2
			},{
			"titleName":"不羁之风",
			"describe":"看不见的那只眼在隐隐作痛。"+"<br/>"+"里面有自己的过去。"+"<br/>"+"以及 ……",
			"name":"夏侯惇",
			"sysId":52,
			"coverImg":"images/list/list_img52.jpg",
			"status":2
			},{
			"titleName":"铁血都督",
			"describe":"她的出现像一道微风，让我得以放下重责自由呼吸；"+"<br/>"+"也揭开了惨淡的未来，让我陷入深渊。",
			"name":"周瑜",
			"sysId":53,
			"coverImg":"images/list/list_img53.jpg",
			"status":2
			},{
			"titleName":"无双之魔",
			"describe":"不能成人，那就成魔吧。"+"<br/>"+"活下去，之后…… ",
			"name":"吕布",
			"sysId":54,
			"coverImg":"images/list/list_img54.jpg",
			"status":2
			}
		]
	}
}

listData.listData09= {
	"success":"成功",
	"data":{
		"pageStart":9,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"永恒之月",
			"describe":"渴求青春美貌，并愿意付出一切代价。",
			"name":"芈月",
			"sysId":55,
			"coverImg":"images/list/list_img55.jpg",
			"status":2
			},{
			"titleName":"最终兵器",
			"describe":"能够作为臣子，为他冲锋在前，这便足矣。",
			"name":"白起",
			"sysId":56,
			"coverImg":"images/list/list_img56.jpg",
			"status":2
			},{
			"titleName":"善恶怪医",
			"describe":"无论付出多大代价，他终究会超越那个人，并给予他致命一击。",
			"name":"扁鹊",
			"sysId":57,
			"coverImg":"images/list/list_img57.jpg",
			"status":2
			},{
			"titleName":"逆流之时",
			"describe":"这个害羞的少年将兵法与机关术天才的结合在一起。",
			"name":"孙膑",
			"sysId":58,
			"coverImg":"images/list/list_img58.jpg",
			"status":2
			},{
			"titleName":"野蛮之锤",
			"describe":"强健，美貌（自称），意志坚定（公认），我行我素的夺宝猎人。",
			"name":"钟无艳",
			"sysId":59,
			"coverImg":"images/list/list_img59.jpg",
			"status":2
			},{
			"titleName":"信念之刃",
			"describe":"千百年来，延续着雇佣刺客命运的荆氏一族的最后一人，终将是为了自己和所挚爱的亲人，挥出致命的一剑。",
			"name":"阿轲",
			"sysId":60,
			"coverImg":"images/list/list_img60.jpg",
			"status":2
			}
		]
	}
}

listData.listData10= {
	"success":"成功",
	"data":{
		"pageStart":10,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"叛逆吟游",
			"describe":"以完美的琴音，狂放不羁的个性征服了人们——尤其是纯情的少女。",
			"name":"高渐离",
			"sysId":61,
			"coverImg":"images/list/list_img61.jpg",
			"status":2
			},{
			"titleName":"暴走机关",
			"describe":"似乎，蓉城小霸王的继承者之路，依旧漫漫……",
			"name":"刘禅",
			"sysId":62,
			"coverImg":"images/list/list_img62.jpg",
			"status":2
			},{
			"titleName":"逍遥梦幻",
			"describe":"啊，你问我活在梦里是否感到快乐？",
			"name":"庄周",
			"sysId":63,
			"coverImg":"images/list/list_img63.jpg",
			"status":2
			},{
			"titleName":"机关造物",
			"describe":"鲁班大师的年龄？秘密！鲁班大师的身高？秘密！鲁班大师的真实面目？秘密！",
			"name":"鲁班七号",
			"sysId":64,
			"coverImg":"images/list/list_img64.jpg",
			"status":2
			},{
			"titleName":"千金重弩",
			"describe":"共同的喜好、共同的愿望、共同的理想以及共同的……是那种叫做爱情的东西吗？ ",
			"name":"孙尚香",
			"sysId":65,
			"coverImg":"images/list/list_img65.jpg",
			"status":2
			},{
			"titleName":"王者独尊",
			"describe":"朕是天生的君主，手握最强的利剑。朕将统一六国，君临天下！",
			"name":"嬴政",
			"sysId":66,
			"coverImg":"images/list/list_img66.jpg",
			"status":2
			}
		]
	}
}

listData.listData11= {
	"success":"成功",
	"data":{
		"pageStart":11,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"魅力之狐",
			"describe":"据说人类都有“爱”这种感情。可什么才是真正的爱？她不敢肯定。因为自己没有心。",
			"name":"妲己",
			"sysId":67,
			"coverImg":"images/list/list_img67.jpg",
			"status":2
			},{
			"titleName":"和平守望",
			"describe":"亲手建造的和平，也将亲手捍卫！",
			"name":"墨子",
			"sysId":68,
			"coverImg":"images/list/list_img68.jpg",
			"status":2
			},{
			"titleName":"苍天翔龙",
			"describe":"今天的朋友可能是明日的敌人，过去的对手也能摇身一变成为如今的同盟。",
			"name":"赵云",
			"sysId":69,
			"coverImg":"images/list/list_img69.jpg",
			"status":2
			},{
			"titleName":"恋之微风",
			"describe":"天生就能将复杂的魔道运用自如，那种天赋就流淌在她的血液里，无需教导也挥之不去。",
			"name":"小乔",
			"sysId":70,
			"coverImg":"images/list/list_img70.jpg",
			"status":2
			}
		]
	}
}

listData.listData12= {
	"success":"成功",
	"data":{
		"pageStart":12,
		"pageSize":6,
		"count":71,
		"list":[{
			"titleName":"正义爆轰",
			"describe":"他已做好了全部的准备，以热情和勇气来向自己的朋友证明他们信任的价值！也许，还有别的什么值得期待…… ",
			"name":"廉颇",
			"sysId":71,
			"coverImg":"images/list/list_img71.jpg",
			"status":2
			}
		]
	}
}
